### ISSUE TITLE
Build Xcode substitute

### ISSUE THREAD

**Issue by besarthoxhaj** [besarthoxhaj/learn-objective-c#4]
## Todo
- [ ] understand and learn `.xcodeproj` format in order to replicate it
- [ ] do the same for `Info.plist`
- [ ] use and understand `plutil` command
- [ ] use [premake-core](https://github.com/premake/premake-core)

## Resources
- https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html

- https://www.theiphonewiki.com/wiki/Plutil
